name = "benwiddowson-homepage"
compatibility_date = "2024-09-23"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "website-homepage"
database_id = "2db671d8-55d2-4958-9f9b-1f017b8571f4"
